# Site settings
website: https://richardbrown384.github.io
basewebsite: /mostly-incomplete-mips-jit-tutorial
title: The Mostly Incomplete MIPS JIT Tutorial
description: >-
  A series of blog articles outlining the basics of writing
  an x64 JIT for the MIPS 3000 family of processors.
github_username: RichardBrown384

# Build settings
theme: minima
plugins:
  - jekyll-feed